# All values in no of frames
BACKGROUND_COLOR: "#EEECEE"
FRAME_RATE: 60
SCREEN_RES: [1920, 1080]
FIX_CROSS_TIME: 96
TRIALS: 60
TRAINING_TRIALS: 8
STIM_SIZE1: 708
STIM_SIZE2: 147
REACTION_TIME: 90
REACTION_KEYS: [left, right]


