# All values in no of frames
BACKGROUND_COLOR: #EEECEE
FRAME_RATE: 60
SCREEN_RES: [1920, 1080]
FIX_CROSS_TIME: 96 
NO_TRAINING_TRIALS: [5, 1]
TRIALS: 60
TRAINING_TRIALS: 8
FIX_CROSS_COLOR: black
STIM_LETTERS: ←→↑↓
STIM_SIZE1: 708
STIM_SIZE2: 147
STIM_SHIFT: 600
STIM_TIME: [9, 15, 21] 
REACTION_TIME: 90
MASK_TIME: 10
REACTION_KEYS: [left, right]
REACTION_KEYS_SEP: 30
STIM_COLOR: dimgray

